name: Build ProductService

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Stop IIS App
        shell: powershell
        run: |
          Stop-Website "ProductService"
          Stop-WebAppPool "ProductPool"

      - name: Deploy
        shell: powershell
        run: Copy-Item "publish\*" "C:\inetpub\ProductService" -Recurse -Force

      - name: Start IIS App
        shell: powershell
        run: |
          Start-WebAppPool "ProductPool"
          Start-Website "ProductService"